// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mohtthappjwtvmvcjxmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vaHR0aGFwcGp3dHZtdmNqeG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDY1NjcsImV4cCI6MjA3MDA4MjU2N30.xaTB8ghEl_yPq0b0OplU_c4l_jaT7yS1x4eiOuqtCY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});