name: Build and Release Desktop App

# Build on PRs (for testing) and main pushes (for potential releases)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manual releases via tags
  push:
    tags: [ 'v*' ]

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run electron:build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Always upload build artifacts (even if later steps fail)
      - name: Upload build artifacts
        if: always()  # This ensures artifacts are uploaded even if build has issues
        uses: actions/upload-artifact@v4
        with:
          name: zawali-finance-mac-${{ github.sha }}
          path: dist-electron/*.dmg

      # Only create releases when you push a version tag
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist-electron/*.dmg
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}