name: Build and Release Desktop App

on:
  push:
    tags: ['v*']  # Only build on version tags
  pull_request:
    branches: [main]

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build and package the app
      - name: Build Electron app
        run: npm run electron:build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts for debugging
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zawali-finance-mac-${{ github.ref_name }}
          path: |
            dist-electron/*.dmg
            dist-electron/*.blockmap
            dist-electron/latest-mac.yml

      # Create GitHub release with ALL necessary files
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-electron/*.dmg
            dist-electron/*.blockmap
            dist-electron/latest-mac.yml
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}